FROM node:20-alpine


WORKDIR /bms

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

RUN npm install -g pnpm

COPY ./packages  ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json
COPY ./package.json ./package.json
COPY ./apps/http-server ./apps/http-server

RUN pnpm install



EXPOSE 3002

CMD [ "npm","run","dev:be" ]